name: eloquent
version: 1.1.1
description: eloquent query builder port from PHP Laravel
homepage: https://github.com/insinfo/eloquent_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:  
  intl: '>=0.17.0 <3.0.0'
  #dargres: ^2.2.2 
  dargres: 
    path: ../dargres

dev_dependencies:
  test: ^1.17.12 

  