name: eloquent
descriptio: eloquent query builder port from PHP Laravel

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  #postgres: ^2.5.2
  intl: any
  #dargres: ^2.1.0
  dargres: 
    path: ../dargres

dev_dependencies:
  test: any